require('settings')
require('keymaps')
require('load-plugins')

require('nvimtree-config')
require('tokyonight-config')
require('lualine-config')
require('autopairs-config')
require('colorizer-config')
require('treesitter-config')
require('twilight-config')
require('lightspeed-config')

require('lsp')
require('nvim-go-config')
require('toggleterm-config')
