require('settings')
require('keymaps')
require('load-plugins')

require('nvimtree-config')
require('gruvbox-config')
require('autopairs-config')
require('colorizer-config')
require('treesitter-config')
require('telescope-config')

require('lsp')
require('gitsigns-config')
require('identline-config')
require('nvim-go-config')
require('autocmd-files')
